// <auto-generated />
namespace eComShop.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imgUrladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imgUrladded));
        
        string IMigrationMetadata.Id
        {
            get { return "202006260344572_imgUrl added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
